-- Ensure table exists before inserting
CREATE TABLE IF NOT EXISTS USER_WALLET (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    SYMBOL VARCHAR(255) NOT NULL,
    BALANCE DECIMAL(20,2) NOT NULL
);

-- Initialize user wallet with 50,000 USDT
INSERT INTO USER_WALLET (USER_ID, SYMBOL, BALANCE)
VALUES (1, 'USDT', 50000.00);